# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 350)
        Dialog.setStyleSheet("\n"
"QDialog {\n"
"    background-color: #f3f3f3;\n"
"}\n"
"QWidget#formLayoutWidget {\n"
"    background-color: #f3f3f3;\n"
"}\n"
"QScrollArea, QScrollArea > QWidget {\n"
"    background-color: #f3f3f3;\n"
"}\n"
"QLabel[objectName^=\"_\"] {\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    font-size: 16px;\n"
"}\n"
"QCheckBox {\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsArea = QtWidgets.QScrollArea(Dialog)
        self.settingsArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settingsArea.setWidgetResizable(True)
        self.settingsArea.setObjectName("settingsArea")
        self.formLayoutWidget = QtWidgets.QWidget()
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 480, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(30, 20, 30, 20)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self._common = QtWidgets.QLabel(self.formLayoutWidget)
        self._common.setStyleSheet("font-weight: bold; color: #2c3e50; font-size: 14px;")
        self._common.setObjectName("_common")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self._common)
        self.precisionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.precisionLabel.setObjectName("precisionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.precisionLabel)
        self.precisionCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.precisionCombo.setObjectName("precisionCombo")
        self.precisionCombo.addItem("")
        self.precisionCombo.addItem("")
        self.precisionCombo.addItem("")
        self.precisionCombo.addItem("")
        self.precisionCombo.addItem("")
        self.precisionCombo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.precisionCombo)
        self.precisionSet = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.precisionSet.setMaximum(12)
        self.precisionSet.setProperty("value", 12)
        self.precisionSet.setObjectName("precisionSet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.precisionSet)
        self._display = QtWidgets.QLabel(self.formLayoutWidget)
        self._display.setStyleSheet("font-weight: bold; color: #2c3e50; font-size: 14px;")
        self._display.setObjectName("_display")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self._display)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.checkUnusual = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkUnusual.setObjectName("checkUnusual")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkUnusual)
        self._debug = QtWidgets.QLabel(self.formLayoutWidget)
        self._debug.setStyleSheet("font-weight: bold; color: #2c3e50; font-size: 14px;")
        self._debug.setObjectName("_debug")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self._debug)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.startDebug = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.startDebug.setObjectName("startDebug")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.startDebug)
        self.output2infoArea = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.output2infoArea.setObjectName("output2infoArea")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.output2infoArea)
        self.settingsArea.setWidget(self.formLayoutWidget)
        self.verticalLayout.addWidget(self.settingsArea)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setContentsMargins(30, 6, 30, 16)
        self.buttons.setSpacing(8)
        self.buttons.setObjectName("buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons.addItem(spacerItem)
        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset.setStyleSheet("color: red;\n"
"")
        self.reset.setObjectName("reset")
        self.buttons.addWidget(self.reset)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setObjectName("cancel")
        self.buttons.addWidget(self.cancel)
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setStyleSheet("")
        self.ok.setObjectName("ok")
        self.buttons.addWidget(self.ok)
        self.verticalLayout.addLayout(self.buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self._common.setText(_translate("Dialog", "运算设置"))
        self.precisionLabel.setText(_translate("Dialog", "常数精度"))
        self.precisionCombo.setItemText(0, _translate("Dialog", "高中物理大题（1位有效数字）"))
        self.precisionCombo.setItemText(1, _translate("Dialog", "高中普通计算（2位有效数字）"))
        self.precisionCombo.setItemText(2, _translate("Dialog", "大学标准（4位有效数字）"))
        self.precisionCombo.setItemText(3, _translate("Dialog", "大学高精度（6位有效数字）"))
        self.precisionCombo.setItemText(4, _translate("Dialog", "最高精度（12位有效数字）"))
        self.precisionCombo.setItemText(5, _translate("Dialog", "自定义（在下方输入框填写有效数字位数）"))
        self._display.setText(_translate("Dialog", "显示设置"))
        self.label.setText(_translate("Dialog", "右侧面板"))
        self.checkUnusual.setText(_translate("Dialog", "显示不常用单位/常量/函数"))
        self._debug.setText(_translate("Dialog", "调试设置"))
        self.label_5.setText(_translate("Dialog", "调试模式"))
        self.startDebug.setText(_translate("Dialog", "输出调试日志"))
        self.output2infoArea.setText(_translate("Dialog", "输出处理日志至信息区"))
        self.reset.setText(_translate("Dialog", "重置"))
        self.cancel.setText(_translate("Dialog", "取消"))
        self.ok.setText(_translate("Dialog", "确定"))
